### ISSUE TITLE
double blocage dans l'indexation des mots arabes

### ISSUE THREAD

**Issue by ralessi** [maieul/indextools#1]
Soit le mwe suivant:

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{amsmath}
\defaultfontfeatures{Ligatures=TeX}
\setmainfont{Linux Libertine O}

\usepackage{indextools}
\usepackage{eledmac}
\makeindex[noautomatic, name=arabe, title={Index des mots arabes}]
\usepackage{hyperref}

\usepackage{polyglossia}
\setdefaultlanguage{french}
\setotherlanguage{arabic}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}
\usepackage[voc]{arabxetex}
\newcommand{\ta}{\textarabic}
\let\aemph\veryundefinedcommand

\begin{document}

\beginnumbering
\pstart
Je ne sais si cela va
marcher... \ta{\edindex[arabe]{\ta{دخل}!f01@\ta{daxala}}daxala mubtasimaN}
\pend
\endnumbering

\printindex[arabe]
\end{document}
```
# Premier blocage

Si je tente de le compiler, j'obtiens l'erreur suivante:

```
Package eledmac Warning: Can't find line-list file mwe-mk3.1 on input line 27.

! Use of \\@wredindex doesn't match its definition.
\kernel@ifnextchar ...rved@d =#1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.32   mubtasimaN}
```

En revanche, si je commente la ligne `\usepackage{hyperref}` la compilation se fait. Même comportement avec imakeidx.

La compilation d'un index arabe est complexe. Explication courte: les mots arabes sont classés par racine. Sous chaque entrée, on doit trouver, autant de sous-entrées qu'on a de formes différentes de la même racine. Dans le mwe ci-dessus, j'obtiens ceci en écrivant dans le tag d'index: `!f01@\ta{daxala}`. Autrement dit: «première forme, à classer sous “daxala”».

Dans mon cas, pour que tout fonctionne, je dois avec l'exemple suivant (donc sans hyperref, hélas) obtenir le fichier `arabe.ixd` suivant:

```
\indexentry{\bgroup \catcode `^=11\relax \catcode `_=11\relax \text@arab {دخل}!f01@\bgroup \catcode `^=11\relax \catcode `_=11\relax \text@arab {daxala}}{1-1}
```

Ensuite, je fais dans tout le fichier une recherche-remplacement. Je recherche:

```
\bgroup \catcode `^=11\relax \catcode `_=11\relax \text@arab
```

que je remplace tout simplement par `\ta`. Puis je fais `makeindex arabe` et le tour est joué. C'est ce qui me conduit au deuxième blocage.
# Deuxième blocage

C'est tout simple. Étant entendu que `hyperref`  est désactivé, `indextools` ne produit pas la sous-entrée. Alors que `imakeidx` produit la sous-entrée...
# Épilogue

Si maintenant j'utilise la fonction d'indexation intégrée de `memoir`, tout marche: entrées, sous-entrées et même avec `hyperref`.

**Comment by maieul** [comment]
le premier probl�me est plus li� � eledmac, qui n�cessite des commandes robustes pass� en argument, et pas des commandes fragiles, en tout cas pas toute.

Dans le cas pr�sent, un robustify suffit. Voir 0ea1825 Du coup ton .idx est directement avec \textarabic dedans, et cela ne pose plus de souci avec du noautomatic.
Le deuxi�me probl�me m'�tonne plus. Je regarde

**Comment by maieul** [comment]
le deuxième point est tout betement lié au fait que indextools, contrairement à imakeix, fait bien le colonnage lorsque bidi est chargé. Comme tu n'a qu'une entré, l'entrée et la sous entrée se trouve sur deux colonnes ≠.

Essai avec plus d'entrée tu verra que cela fonctionne.

Concernant le 1er point, je vais faire en sorte que tu n'ai pas à déclarer des commandes robustes avec \edindex. Ce n'est pas normal.

**Comment by ralessi** [comment]
Merci tout de même pour l'idée de déclarer cette commande robuste. Je n'y avais pas pensé.

Je viens d'essayer avec deux entrées, et ça marche parfaitement, avec une lecture de l'index arabe dans le bon sens. Magnifique. Et du coup, hyperref marche aussi. J'ai ajouté un deuxième index de mots «latins», et il se met dans l'ordre LTR.

Je suis enchanté, merci mille fois! Cela sonne pour moi le décrochage de memoir.

**Comment by ralessi** [comment]
Juste une remarque: il me semble que `\edindex[truc]{machin}machin` produit une espace plus grande devant le mot machin dans le pdf. Non?

**Comment by maieul** [comment]
apr�s test c'est plus complexe que je penser d'adapter eledmac. J'ai pas vraiment de tps dessus, et comme c'est un probl�me qui se r�soud assez facilement, je laisse tomber. Utilise le robustify. Je verifie pour le probl�me d'espace

**Comment by ralessi** [comment]
Le robustify fait parfaitement le job. Tu dois être bien occupé par eledpub à ce que je vois!

**Comment by maieul** [comment]
bof, non, je dois faire cela ce week-end, mais j'ai aussi des projets associatif et ma th�se...

**Comment by ralessi** [comment]
Ah! Bon courage! Mon travail d'édition est très lent aussi: je compatis.

**Comment by maieul** [comment]
la branch 1.18.0 de eledmac (dont j'attend la correction de rebecca) devrait r�soudre le probl�me. On clos le ticket.

**Comment by maieul** [comment]
mon directeur vient de me dire qu'apparement brepols acceptait d�sormais le .tex pour les �ditions critiques (� confirmer�)

**Comment by ralessi** [comment]
Je viens de tenter de compiler toute une section de mon édition remplie de marques d'index, et je tombe de nouveau sur:

```
Section 1R  (./master.1R) (./master.eledsec1R)
! Use of \\@wredindex doesn't match its definition.
\kernel@ifnextchar ...rved@d =#1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.299 ...�ου}\Afootnote{\emph{ibid.}(17a 38 4)}}
```

dès la première marque d'index. Même chose avec `imakeidx`, avec ou sans `hyperref`. Je ne comprends pas ce qui se passe. La même chose sur le mwe d'hier semblait passer dès qu'au moins deux mots étaient indexés, et là j'en ai plus de mille!

**Comment by maieul** [comment]
hum,

bon dans tous les cas le pb se situe au niveau de eledmac, pas de indextools. D'autre part, tu es sur d'avoir bien conserv� / install� la robustess?

**Comment by ralessi** [comment]
Je vérifie... je ne suis pas certain de ne pas avoir commis une erreur.

**Comment by ralessi** [comment]
En effet, je n'avais pas tout «robustifié»: ça passe!

Étrangement, les pages des index ne sont pas des hyperliens alors que hyperref est bien actif. Alors que les hyperliens sont actifs dans le mwe. Mais c'est très accessoire!

Désolé de ce billet intempestif!

**Comment by ralessi** [comment]
Pour les hyperliens, j'ai ceci dans les fichiers `.ind`:

```
  \item ἀδελφιδῆ, \hyperlinkR{$&581}{15-6}
  \item ἀθρόος, \hyperlinkR{$&561}{15-4}
  \item αἰδοῖος, \hyperlinkR{$&613}{15-8}
  \item αἷμα, \hyperlinkR{$&509}{13-13}
  \item αἱμορραγίη, \hyperlinkR{$&659}{15-12}
  \item ἀκατάστατος, \hyperlinkR{$&202}{9-14}, 
        \hyperlinkR{$&203}{9-14}
```

etc.

**Comment by maieul** [comment]
a tu devrais avoir \hyperlink. C'est un bug. Ouvre un ticket sur eledmac.

**Comment by maieul** [comment]
je viens d'ouvrir. On suit là bas le bug.

**Comment by ralessi** [comment]
Ok
