### ISSUE TITLE
Feature request: upmendex as package option

### ISSUE THREAD

**Issue by jjtorrens** [maieul/indextools#15]
The **upmendex** program has become a very convenient replacement of **MakeIndex** since UTF is now the default encoding in LaTeX. The current version of **indextools** does not allow to directly call **upmendex**, since `upmendex` is not recognized as a package option nor a valid value for the `program` key in the `\makeindex` command. As a workaround, the following code loads **indextools** and makes **upmendex** the default indexing program:

```
\usepackage{indextools} 
\makeatletter \def\indtl@progdefault{upmendex} \makeatother
```

So, could you add `upmendex` as a valid option for **indextools**? It would be very helpful.
Thank you

**Comment by maieul** [comment]
Please try the branch `issue_15_upmendex` (download the branch zip, run latex in the .ins file, when put the .sty file along your main .tex file).

**Comment by jjtorrens** [comment]
Many thanks for the quick answer. Now **indextools** admits `upmendex` as an option, but not yet as a valid value for the key `program ` in `\makeindex`. Example:
```
\documentclass[a4paper]{article}

% The following code works as expected
% Terms in "Numbers" ordered by upmendex
% Terms in "Days" ordered by MakeIndex
\usepackage[upmendex]{indextools}
\makeindex[name=numbers,title=Numbers]
\makeindex[name=days,title=Days,program=makeindex]

% However, the following code does not work:
%\usepackage{indextools}
%\makeindex[name=numbers,title=Numbers]
%\makeindex[name=days,title=Days,program=upmendex]

\begin{document}
  
Numbers: one, two, three\ldots
\index[numbers]{one}\index[numbers]{two}\index[numbers]{three}

Days: monday, tuesday, wednesday\ldots
\index[days]{monday}\index[days]{tuesday}\index[days]{wednesday}

\printindex[numbers]
\printindex[days]

\end{document}
```

**Comment by maieul** [comment]
Please try new version of the branch.

**Comment by jjtorrens** [comment]
Now it works. Thanks!
