### ISSUE TITLE
Supporting xindex

### ISSUE THREAD

**Issue by wujastyk** [maieul/indextools#16]
Could you add support for [xindex](https://ctan.org/pkg/xindex?lang=en), perhaps with the user command below?
```
\usepackage[xindex] {indextools} 
```
Thanks!

**Comment by maieul** [comment]
xindex, xindex, upmendex... how many index engine does it exist ?

I will do... but it is so sad that the question happens just after a new version which provide upmendex support...

**Comment by maieul** [comment]
Please try  branch issue16_xindex

**Comment by wujastyk** [comment]
> xindex, xindex, upmendex... how many index engine does it exist ?
> 
> I will do... but it is so sad that the question happens just after a new version which provide upmendex support...

Personally, I only became aware  of indextools because of the latest TeXlive update.  I try to scan updates and additions as they come in via tlmgr, but it's only a rough scan.  
Thanks for this. I currently have a package clash of some sort  ("no line here to end" after a couple of paragraphs), but I think it's bidi <-> polyglossia/persian, and not imakeidx.  Swapping imakeidx for indextools hasn't helped my particular issue.

**Comment by maieul** [comment]
So, may I publish the new version ? Message ID: 
***@***.***>

**Comment by wujastyk** [comment]
> So, may I publish the new version ? Message ID: ***@***.***>

I've installed it and run it; seems fine so far.  But I need to do some testing on real indexing over the weekend.  I'll write again.

**Comment by wujastyk** [comment]
I've done some testing with [xindex]{indextools} and I see no problems.  Thank you so much, Maïeul!
