### ISSUE TITLE
Problem with noclearpage option of indexsetup?

### ISSUE THREAD

**Issue by sonator** [maieul/indextools#2]
In the following MWEs no index entry will be accepted. But, after removing the noclearpage option of the indexsetup all entries are found and typeset correctly. I have used pdflatex.exe.

Please have a look on the MWEs. Thank you!

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex]{indextools}
\indexsetup{level=\section*,toclevel=section,noclearpage}

\makeindex[name=res,title=Index rerum]
\makeindex[name=pers,title=Index personarum]

\newcommand{\fn}[1]{#1\textit{n}}

\begin{document}

Experimentum\index[res]{experimentum} istud Johannis\index[pers]{Johannes} est\footnote{Nota pedis\index[res]{nota pedis|fn} experimentalis}.

\printindex[res]
\printindex[pers]

\end{document}

---

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex]{indextools}
\indexsetup{level=\section*,toclevel=section,noclearpage}

\usepackage[series={A},noeledsec,noend]{reledmac}

\makeindex[name=res,title=Index rerum]
\makeindex[name=pers,title=Index personarum]

\newcommand{\fn}[1]{#1\textit{n}}

\begin{document}

\begin{ledgroup}
\beginnumbering
\pstart
Experimentum\index[res]{experimentum} istud Johannis\index[pers]{Johannes} est\footnoteA{Nota pedis\index[res]{nota pedis|fn} experimentalis}.
\pend 
\endnumbering
\end{ledgroup}

\printindex[res]
\printindex[pers]

\end{document}

**Comment by maieul** [comment]
I was anxious people find this bug.

For now, I have no idea of how to solve it. An immediate writing is not 
a good idea (cf http://tex.stackexchange.com/a/115933/7712 and the 
remarks about page number).

There is only one solution: allow to have a page break before the first 
index, using \newpage.

**Comment by sonator** [comment]
Thank you very much for answering so quickly! The proposed solution is convenient. 

The starting point of my tests was the effort to set in the index an italic n behind the page numbers of entries, which are placed in a footnote of normal text or in a familiar note of numbered text. 

There are two problems: 
1. xindy is refusing to cooperate with \newcommand{\fn}[1]{#1\textit{n}}. 
2. The solution proposed in the indextools handbook p. 12-13 is failing in the MWE below cited. In my code something must be wrong. I have replaced \pretocommand by \pretocmd, because \pretocommand causes error messages. 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage{letltxmacro}
\usepackage[xindy,splitindex]{indextools}%
\indexsetup{level=\section*,toclevel=section}

\usepackage[series={A},noeledsec,noend,xindy,xindy+hyperref]{reledmac}
\usepackage[hyperindex=false]{hyperref}

%\newcommand{\fn}[1]{#1\textit{n}}

\makeatletter
\LetLtxMacro\orig@@index\index
\newcommand\nindex[1]{\orig@@index{#1|innote}}
\newcommand\innote[1]{#1\textit{n}}

\makeindex[name=res,title=Index rerum]
\makeindex[name=nom,title=Index nominum]

\AtBeginDocument{%
\pretocmd{\@footnotetext}{\let\index\nindex}{}{}
}
\makeatother

\begin{document}

Textus usitatus\footnote{nota communis\nindex[res]{nota communis}}.

\begin{ledgroup}
\beginnumbering
\pstart
Textus\index[res]{textus} a reledmac\footnoteA{Nota familiaris reledmacensis\nindex[nom]{reledmac}} numeratus.
\pend
\endnumbering
\end{ledgroup}

\printindex[res]
\printindex[nom]

\end{document}

**Comment by maieul** [comment]
1) indeed it was an handbook bug. But it concerns (normally° only ledmac, not eledmac or reledmac.
2) please open an issue on reledmac page. It is related to reledmac + xindy, not indextools.

**Comment by sonator** [comment]
THANK YOU! I transfer the case to the reledmac page.
