### ISSUE TITLE
notenumber option does not work in a single index

### ISSUE THREAD

**Issue by sonator** [maieul/indextools#5]
Does the notenumber option only work in combination with a symbolic name for an index? 

When no symbolic name is specified the MWE does not run. And the index command in the normal footnote causes an error message. Without the notenumber option it works. 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex,notenumber]{indextools}
\usepackage[series={A,B,C},noeledsec,noend]{reledmac}
\usepackage{reledpar}
\makeindex[title=Index personarum]

\begin{document}

\chapter{Carolus Magnus et alii quamplures}
Carolus Magnus\index{Carolus Magnus}, 
Ludovicus Pius\footnote{Ludovicus Pius\index{Ludovicus Pius}}

\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
Pippinus Maior\footnoteA{Pippinus Maior\index{Pippinus Maior}}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Pippinus Minor\footnoteA{Pippinus Minor\index{Pippinus Minor}}.
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\printindex

\end{document}

**Comment by maieul** [comment]
please try branch "issue5"

**Comment by sonator** [comment]
The index commands in the normal text and normal footnote are accepted. The index commands inside the familiar notes are ignored. 

And I get this error message twice: 

! Missing number, treated as zero.
<to be read again> 
                   {
l.38 \Columns

A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up`weird error' in the index to The TeXbook.)

I am using pdflatex under Win7.

**Comment by maieul** [comment]
with this MWE ? or an other one?

**Comment by sonator** [comment]
Yes with this MWE.

**Comment by maieul** [comment]
hum. I don't have. Could I have the results of a \listfiles?

**Comment by sonator** [comment]
The result of a \listfiles: 

 _File List_
 scrbook.cls    2015/07/02 v3.18 KOMA-Script document class (book)
scrkbase.sty    2015/07/02 v3.18 KOMA-Script package (KOMA-Script-dependent basics and keyval usage)
 scrbase.sty    2015/07/02 v3.18 KOMA-Script package (KOMA-Script-independent basics and keyval usage)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
scrlfile.sty    2015/07/02 v3.18 KOMA-Script package (loading files)
tocbasic.sty    2015/07/02 v3.18 KOMA-Script package (handling toc-files)
scrsize11pt.clo    2015/07/02 v3.18 KOMA-Script font size class option (11pt)
typearea.sty    2015/07/02 v3.18 KOMA-Script package (type area)
inputenc.sty    2015/03/17 v1.2c Input encoding file
    utf8.def    2014/09/29 v1.1m UTF-8 support for inputenc
   t1enc.dfu    2014/09/29 v1.1m UTF-8 support for inputenc
  ot1enc.dfu    2014/09/29 v1.1m UTF-8 support for inputenc
  omsenc.dfu    2014/09/29 v1.1m UTF-8 support for inputenc
 fontenc.sty
   t1enc.def    2005/09/27 v1.99g Standard LaTeX file
   babel.sty    2014/09/25 3.9l The Babel package
 bblopts.cfg    2006/07/31 v1.0 MiKTeX 'babel' configuration
  german.ldf    2014/10/10 v2.7b German support for babel (traditional orthography)
indextools.sty    2015/11/21 v1.5.1 Package for typesetting indices in a synchronous mode
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
  xpatch.sty    2012/10/02 v0.3 Extending etoolbox patching commands
   expl3.sty    2015/06/15 v5630 L3 programming layer (loader) 
expl3-code.tex    2015/06/15 v5630 L3 programming layer 
l3unicode-data.def    2015/03/01 v5544 L3 Unicode data
l3pdfmode.def    2015/05/21 v5613 L3 Experimental driver: PDF mode
  xparse.sty    2015/06/15 v5630 L3 Experimental document command parser
etoolbox.sty    2015/05/04 v2.2 e-TeX tools for LaTeX (JAW)
multicol.sty    2015/03/31 v1.8m multicolumn formatting (FMi)
reledmac.sty    2015/11/20 v2.6.0 typeset critical edition
   xargs.sty    2008/03/22 v1.1  extended macro definitions  (mpg)
    etex.sty    2015/03/02 v2.1 eTeX basic definition package (PEB,DPC)
  suffix.sty    2006/07/15 1.5a Variant command support
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
ragged2e.sty    2009/05/21 v2.1 ragged2e Package (MS)
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
reledpar.sty    2015/11/20 v2.6.1 reledmac extension for parallel texts
  xspace.sty    2014/10/28 v1.13 Space after command names (DPC,MH)
letltxmacro.sty    2010/09/02 v1.4 Let assignment for LaTeX macros (HO)
  t1cmss.fd    2014/09/29 v2.5h Standard LaTeX font definitions
IndexFN4.1
IndexFN4.1R
IndexFN4.ind

---

**Comment by maieul** [comment]
hum, I have not these one. 

 scrbook.cls    2015/10/03 v3.19a KOMA-Script document class (book)
scrkbase.sty    2015/10/03 v3.19a KOMA-Script package (KOMA-Script-dependent ba
sics and keyval usage)
 scrbase.sty    2015/10/03 v3.19a KOMA-Script package (KOMA-Script-independent 
basics and keyval usage)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
scrlfile.sty    2015/10/03 v3.19a KOMA-Script package (loading files)
tocbasic.sty    2015/10/03 v3.19a KOMA-Script package (handling toc-files)
scrsize11pt.clo    2015/10/03 v3.19a KOMA-Script font size class option (11pt)
typearea.sty    2015/10/03 v3.19a KOMA-Script package (type area)
inputenc.sty    2015/03/17 v1.2c Input encoding file
    utf8.def    2015/09/07 v1.1p UTF-8 support for inputenc
   t1enc.dfu    2015/09/07 v1.1p UTF-8 support for inputenc
  ot1enc.dfu    2015/09/07 v1.1p UTF-8 support for inputenc
  omsenc.dfu    2015/09/07 v1.1p UTF-8 support for inputenc
 fontenc.sty
   t1enc.def    2005/09/27 v1.99g Standard LaTeX file
   babel.sty    2015/08/03 3.9m The Babel package
  german.ldf    2014/10/10 v2.7b German support for babel (traditional orthogra
phy)
indextools.sty    2015/11/21 v1.5.1 Package for typesetting indices in a synchr
onous mode
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
  xpatch.sty    2012/10/02 v0.3 Extending etoolbox patching commands
   expl3.sty    2015/11/04 v6224 L3 programming layer (loader) 
expl3-code.tex    2015/11/04 v6224 L3 programming layer 
l3unicode-data.def    2015/07/20 v5676 L3 Unicode data
l3pdfmode.def    2015/09/10 v5983 L3 Experimental driver: PDF mode
  xparse.sty    2015/11/04 v6224 L3 Experimental document command parser
etoolbox.sty    2015/05/04 v2.2 e-TeX tools for LaTeX (JAW)
multicol.sty    2015/08/19 v1.8n multicolumn formatting (FMi)
reledmac.sty    2015/11/20 v2.6.0 typeset critical edition
   xargs.sty    2008/03/22 v1.1  extended macro definitions  (mpg)
  suffix.sty    2006/07/15 1.5a Variant command support
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
ragged2e.sty    2009/05/21 v2.1 ragged2e Package (MS)
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
reledpar.sty    2015/11/20 v2.6.1 reledmac extension for parallel texts
  xspace.sty    2014/10/28 v1.13 Space after command names (DPC,MH)
letltxmacro.sty    2010/09/02 v1.4 Let assignment for LaTeX macros (HO)
  t1cmss.fd    2014/09/29 v2.5h Standard LaTeX font definitions

I am installing  a virtualbox with miktex in my computer, but could you try updating your installation? I have no problem in the MWE.

**Comment by sonator** [comment]
Yes, I try an update and will give a feedback!

**Comment by sonator** [comment]
It is not a good day! The miktex update was unsuccessful. miktex reported an error: The operation failed for some reason. Perhaps I should try a completely new installation tomorrow. Sorry for taking up your time.

**Comment by maieul** [comment]
yes, it is not a good day. I was not able to install miktex on my computer. the operation failed too :-(

That is very strange you get error. Please send me the .log

**Comment by sonator** [comment]
The log file is too long to be send as a comment. And GitHub does not support the file format, when I try to attach it. Can I use an email address or send it as message via geekographie?

**Comment by maieul** [comment]
myfirstname@myfirstname.net

**Comment by maieul** [comment]
OK. I know. That is "just" because you use the buged version of reledmac/reledpar, which has been corrected on https://github.com/maieul/ledmac/issues/457.

Try with the correct version, i.e this one https://github.com/maieul/ledmac/archive/2.7.0-2.6.2.zip

**Comment by sonator** [comment]
With the current versions I get the same error message. 

The versions according to the log file: 
Package: reledmac 2015/11/28 v2.7.0 typeset critical edition
Package: reledpar 2015/11/28 v2.6.2 reledmac extension for parallel texts

**Comment by maieul** [comment]
do you have deleted your .aux file after updating version ?

**Comment by maieul** [comment]
what about if you delete all indexing command and package ? just to let know if the problem is reledmac/reledpar or not.

**Comment by maieul** [comment]
could you send me a zip containing all you file mentionned in the log?

**Comment by sonator** [comment]
The MWE runs without error, if one deactivate the two lines of the columns, as done in the first version of the MWE. 

The MWE runs without error, too, if one deactivate the unnumbered text, as in the second version.

In both cases indextools warns: 

Package indextools Warning: Undefined index file `' on input line 40.

In line 40 the \Columns command is placed.

---

First version: numbered text deactivated

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex,notenumber]{indextools}
\usepackage[series={A,B,C},noeledsec,noend]{reledmac}
\usepackage{reledpar}
\makeindex[title=Index personarum]

\listfiles

\begin{document}

\chapter{Carolus Magnus et alii quamplures}
Carolus Magnus\index{Carolus Magnus}, 
Ludovicus Pius\footnote{Ludovicus Pius\index{Ludovicus Pius}}

\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
%Pippinus Maior\footnoteA{Pippinus Maior\index{Pippinus Maior}}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
%Pippinus Minor\footnoteA{Pippinus Minor\index{Pippinus Minor}}.
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\printindex

\end{document}

---

Second version: normal text deactivated

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex,notenumber]{indextools}
\usepackage[series={A,B,C},noeledsec,noend]{reledmac}
\usepackage{reledpar}
\makeindex[title=Index personarum]

\listfiles

\begin{document}

\chapter{Carolus Magnus et alii quamplures}
%Carolus Magnus\index{Carolus Magnus}, 
%Ludovicus Pius\footnote{Ludovicus Pius\index{Ludovicus Pius}}

\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
Pippinus Maior\footnoteA{Pippinus Maior\index{Pippinus Maior}}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Pippinus Minor\footnoteA{Pippinus Minor\index{Pippinus Minor}}.
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\printindex

\end{document}

**Comment by sonator** [comment]
Yes, before the tests I have deleted the aux file.

**Comment by maieul** [comment]
Still not able to reproduce the problem. 
Please send my be email a zip containing:
- the NOT working MWE
- all the .cls and .sty files listed in the .log

**Comment by maieul** [comment]
also let me know what is the result of a \fmtversion command.

**Comment by maieul** [comment]
ok. I don't understand why it was working in my computer. I think I was doing to much thing in the sametime. However, just try the (new) new  dev version of reledmac. https://github.com/maieul/ledmac/archive/2.7.0-2.6.2.zip.

**Comment by sonator** [comment]
I can confirm that the MWE and other files are running on my computer without problems, too. And so this sunday has begun beautifully, thank you!

**Comment by maieul** [comment]
ok. I publish now the new version of indextools. For reledmac, it will wait next week, because I have some other things to add.
